name: main
on:
  schedule:
    - cron: "30 0 * * FRI"
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Setup Go environment
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '^1.17.2'
    - name: Build & Push
      run: |
        bash main.sh
